---
strategy: polling
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://comiccaster.xyz/rss/bc
polling_headers: ''
polling_body: ''
id: 248039
custom_fields:
- keyname: doesnt_matter
  name: Daily B.C. Comic
  field_type: author_bio
  description: Displays the daily B.C. comic by Johnny Hart
  github_url: https://github.com/lanrat/trmnl_plugins
  learn_more_url: https://github.com/lanrat/trmnl_plugins/tree/main/B.C.%20Comic
name: Daily B.C. Comic
refresh_interval: 360
