---
strategy: polling
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://comiccaster.xyz/rss/nonsequitur
polling_headers: ''
polling_body: ''
id: 248036
custom_fields:
- keyname: doesnt_matter
  name: Daily Non Sequitur Comic
  field_type: author_bio
  description: Displays the daily Non Sequitur comic by Wiley Miller
  github_url: https://github.com/lanrat/trmnl_plugins
  learn_more_url: https://github.com/lanrat/trmnl_plugins/tree/main/Non%20Sequitur%20Comic
name: Daily Non Sequitur Comic
refresh_interval: 360
