---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: "{}"
polling_verb: get
polling_url: https://www.comicsrss.com/rss/beware-of-toddler.rss
polling_headers: ''
polling_body: ''
id: 131756
custom_fields:
- keyname: doesnt_matter
  name: Beware of Toddler Comic
  category: comics
  field_type: author_bio
  description: Displays the daily Beware of Toddler Comic by George Gant
  github_url: https://github.com/lanrat/trmnl_plugins
  learn_more_url: https://github.com/lanrat/trmnl_plugins/tree/main/Beware%20of%20Toddler%20Comic
name: Beware of Toddler Comic
refresh_interval: 720
