---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://www.litterboxcomics.com/feed/
polling_headers: ''
polling_body: ''
id: 148700
custom_fields:
- keyname: doesnt_matter
  name: Litterbox Comics
  field_type: author_bio
  category: comics
  description: Displays the daily Litterbox comic by Chesca Hause
  github_url: https://github.com/lanrat/trmnl_plugins
  learn_more_url: https://github.com/lanrat/trmnl_plugins/tree/main/Litterbox%20Comics
name: Litterbox Comics
refresh_interval: 720
